version: 2
updates:
  - package-ecosystem: gitsubmodule
    directories:
      - "index.html"
      - "/assets/css/style.css"
      - "/assets/js/script.js"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - sivasoft-cloud
  - package-ecosystem: npm
    directories:
      - "index.html"
      - "/assets/css/style.css"
      - "/assets/js/script.js"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - sivasoft-cloud
  - package-ecosystem: "github-actions"
    directories:
      - "index.html"
      - "/assets/css/style.css"
      - "/assets/js/script.js"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - sivasoft-cloud
