name: Code Formatter
on: [push, workflow_dispatch]

jobs:
  format_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install -g prettier stylelint

      - name: Format HTML, CSS, and JavaScript
        run: |
          # Format HTML files
          npx prettier --write "index.html"

          # Format CSS files
          npx prettier --write "assets/css/style.css"

          # Format JavaScript files
          npx prettier --write "assets/js/script.js"

      - name: Configure Git
        run: |
          git config user.email "sivakumarsivaraja@gmail.com"
          git config user.name "sivasoft-cloud"

      - name: Auto-commit changes
        run: |
          git add .
          git commit -m "Auto: Code Formatted" --signoff
          git remote add origin_with_token "https://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@github.com/sivasoft-cloud/repo2.git"
          git push origin_with_token master
