name: Code Formatter
on: [push, workflow_dispatch]

jobs:
  format_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install -g prettier stylelint

      - name: Format HTML, CSS, and JavaScript
        run: |
          # Format HTML files
          npx prettier --write "/index.html"

          # Format CSS files
          npx prettier --write "assets/css/style.css"

          # Format JavaScript files
          npx prettier --write "assets/js/script.js"

      - uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: "Auto: Code Formatted"
          commit_options: "--signoff"
          repository: .
          commit_user_name: sivasoft-cloud
          commit_user_email: sivakumarsivaraja@gmail.com
          commit_author: sivasoft-cloud <sivakumarsivaraja@gmail.com>
