name: Code Formatter
on: [push, workflow_dispatch]
jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9
      - name: Install Python lint libraries
        run: |
          pip install autopep8 autoflake isort black
      - name: Check for Showstoppers
        run: >
          autopep8 --verbose --in-place --recursive --aggressive --aggressive
          --ignore=W605 .
      - name: Remove Unused Imports and Variables
        run: >
          autoflake --in-place --recursive --remove-all-unused-imports
          --remove-unused-variables --ignore-init-module-imports .
      - name: Lint with Isort and Black
        run: |
          isort .
          black .
      - uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: "Auto: Code Formatted"
          commit_options: "--signoff"
          repository: .
          commit_user_name: SivaSoft
          commit_user_email: sivakumarsivaraja@gmail.com
          commit_author: SivaSoft <sivakumarsivaraja@gmail.com>
